export const allCategories = [
    "Alati",
    "Audio",
    "Elektronika",
    "Fotografija",
    "Filmovi",
    "Građevinski materijali",
    "Hobi",
    "Hrana",
    "Igre",
    "Igracke",
    "Knjige",
    "Kozmetika",
    "Kućni aparati",
    "Laptop",
    "Ljubimci",
    "Mobilni telefoni",
    "Muzički instrumenti",
    "Nameštaj",
    "Nekretnine",
    "Obuća",
    "Odeća",
    "Odeća za decu",
    "Piće",
    "Poslovi",
    "Računari",
    "Sport i rekreacija",
    "Sportska oprema",
    "Tehnika",
    "Telefon",
    "Umetnost",
    "Vozila",
    "Vrt i bašta",
    "Zdravlje"    
];
