export const allCategories = [
    "Sve",
    "Aksesoari",
    "Audio",
    "Časopisi, stripovi",
    "Elektronika",
    "Filmovi",
    "Fotografija",
    "Građevinski materijali",
    "Hobi",
    "Hrana",
    "Igre",
    "Igracke",
    "Knjige",
    "Kozmetika",
    "Kućni aparati",
    "Mašine i alati",
    "Mobilni telefoni",
    "Muzički instrumenti",
    "Nameštaj",
    "Nekretnine",
    "Obuća",
    "Odeća",
    "Odeća za decu",
    "Oprema za decu",
    "Računari",
    "Sport i rekreacija",
    "Sportska oprema",
    "Stvari za bebe",
    "Tehnika",
    "Telefon",
    "Umetnost",
    "Vozila",
    "Vrt i bašta",
    "Zdravlje"
  ]
  